info:
  app:
    name: Vacinas
    description: Vacinas

server:
  port: 80

scheduled:
  cron: 0 0 * * * *

spring:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://@ec2-54-204-28-187.compute-1.amazonaws.com:5432/postgres
    username: postgres
    password: postgres